clear all;
t=0:1:1000;
w1=2*pi/50;
y=sin(w1*t);

t0=t([1:11:length(t)]);
y0=y([1:11:length(t)]);

t1=t([1:27:length(t)]);
y1=y([1:27:length(t)]);


t2=t([1:45:length(t)]);
y2=y([1:45:length(t)]);

figure
set(gcf,...
        'Color',[1 1 1],...
        'InvertHardcopy','on',...
        'MenuBar','none',...
        'PaperUnits','inches',...
        'Units','inches',...
        'PaperOrientation','landscape',...
        'PaperPosition',[0 0 11 8.5],...
        'PaperPositionMode','manual',...
        'PaperType','a4',...
        'Position',[1 1 11 8.5],...
        'Resize','off',...
        'ShareColors','off',...
        'Clipping','on');




subplot(2,1,1),plot(t,y,'+b',t0,y0,'or',t1,y1,'vg',t2,y2,'sm')
legend('f=1','f=11','f=27','f=45')
title('Aumentando o intervalo amostral f')


subplot(2,1,2),plot(t,y,'-b',t0,y0,'-r',t1,y1,'-g',t2,y2,'-m')
title('A partir de um certo ponto obtemos resultados inverossimeis') 
%print -depsc2 exe_pra_nyq.eps