clear all;close all;clc
load redblue

x1 = -3:0.1:3;
y1 = -3:0.1:3;
[x,y] = meshgrid(x1,y1);
[ly,lx] = size(x);

func = x.*exp(-x.^2-y.^2);

figure
set(gcf,...
        'Color',[1 1 1],...
        'InvertHardcopy','on',...
        'PaperUnits','inches',...
        'Units','inches',...
        'PaperOrientation','portrait',...
        'PaperPosition',[0 0 8.5 11],...
        'PaperPositionMode','manual',...
        'PaperType','usletter',...
        'Position',[.2 .2 8.5 11],...
        'ShareColors','off',...
        'Clipping','on');
subplot(211)
contourf(x,y,func,20); hold on; 
caxis([-0.5 0.5])
axis([-3 3 -3 3])
colormap(redblue)
colorbar('horiz')
title('Sem filtro')

subplot(212)
plot(x1,func((length(y1)+1)/2,:),'k','linewidth',2); hold on;grid
axis([-3 3 -0.5 0.5])


% aplicando filtragem 2D de 21 pontos

funcF = smoo2(func,-9999,21,0.5);

figure
set(gcf,...
        'Color',[1 1 1],...
        'InvertHardcopy','on',...
        'PaperUnits','inches',...
        'Units','inches',...
        'PaperOrientation','portrait',...
        'PaperPosition',[0 0 8.5 11],...
        'PaperPositionMode','manual',...
        'PaperType','usletter',...
        'Position',[.2 .2 8.5 11],...
        'ShareColors','off',...
        'Clipping','on');
subplot(211)
contourf(x,y,funcF,20); hold on; 
caxis([-0.5 0.5])
axis([-3 3 -3 3])
colormap(redblue)
colorbar('horiz')
title('Com filtro de 21 pontos')

subplot(212)
plot(x1,funcF((length(y1)+1)/2,:),'k','linewidth',2); hold on;grid
axis([-3 3 -0.5 0.5])






